### ISSUE TITLE
Sending output data

### ISSUE THREAD

**Issue by aradhanacha** [scheb/python-beat-detector#2]
Hi ,
So I was wondering how can I send this output data to other system. can we try sending it to some API

**Comment by scheb** [comment]
You can exchange this class with whatever implementation you need.

https://github.com/scheb/python-beat-detector/blob/master/osc.py

**Comment by aradhanacha** [comment]
okay actually I am new to OSC /audio signalling ,but I found your program very useful.So as per readme file ,I need to change "local host" address to remote IP address to send OSC messages.I tried changing it but remote system is not receiving it.Can you let me know if there is any specific setting needs to be done at remote system or from my system.
Thanks a lot :)

**Comment by scheb** [comment]
There's no specific setting, not that I'd know, but I've only used it with `localhost` so far, never with an actual remote system. You have to make sure the port on the remote system is open and packets aren't blocked by a firewall.

You don't have to use OSC, I'm just using it because the system that I'm sending the signals to is supporting it. You could also exchange the class with a HTTP implementation or whatever you need.

**Comment by aradhanacha** [comment]
oh okay.I thought we need to run script for  osc_server to receive these OSC messages somewhere

**Comment by scheb** [comment]
With "osc_server" you mean the server provided by the OSC Python package that I use? Well, you don't have to use that specific one. Any server unterstanding the OSC protocol is fine.

But as I said before, if you don't feel comfortable with the OSC protocol, change the implementation of that class to something else that you feel comfortable with ;)
